

export const ADD_NEW_VAR_TRANSACTION = 'ADD_NEW_VAR_TRANSACTION';
export const DELETE_TRANSACTION_BUTTONS = 'DELETE_TRANSACTION_BUTTONS';
export const UPDATE_VARIABLE_TRANSACTION_FORM = 'UPDATE_VARIABLE_TRANSACTION_FORM';
export const ADD_NEW_FIXED_TRANSACTION = 'ADD_NEW_FIXED_TRANSACTION';
export const DELETE_FIXED_TRANSACTION_BUTTONS = 'DELETE_FIXED_TRANSACTION_BUTTONS';
export const UPDATE_FIXED_TRANSACTION_FORM = 'UPDATE_FIXED_TRANSACTION_FORM';
export const UPDATE_USER_DATA = 'UPDATE_USER_DATA';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const SET_MINIMUM_SAVINGS = 'SET_MINIMUM_SAVINGS';
export const ADD_TRANS_CATEGORY = 'ADD_TRANS_CATEGORY';