

export const ADD_NEW_VAR_TRANSACTION = 'ADD_NEW_VAR_TRANSACTION';
export const DELETE_TRANSACTION_BUTTONS = 'DELETE_TRANSACTION_BUTTONS';
export const UPDATE_VARIABLE_TRANSACTION_FORM = 'UPDATE_VARIABLE_TRANSACTION_FORM';