

export const ADD_NEW_VAR_TRANSACTION = 'ADD_NEW_VAR_TRANSACTION';
export const DELETE_TRANSACTION_BUTTONS = 'DELETE_TRANSACTION_BUTTONS';
export const UPDATE_VARIABLE_TRANSACTION_FORM = 'UPDATE_VARIABLE_TRANSACTION_FORM';
export const ADD_NEW_FIXED_TRANSACTION = 'ADD_NEW_FIXED_TRANSACTION';
export const DELETE_FIXED_TRANSACTION_BUTTONS = 'DELETE_FIXED_TRANSACTION_BUTTONS';
export const UPDATE_FIXED_TRANSACTION_FORM = 'UPDATE_FIXED_TRANSACTION_FORM';
